app:
  port: 8081
  name: sensor_streaming
  secret_key: "oksecret!1"
mysql:
  host: host.docker.internal
  port: 3306
  driver_name: mysql
  username: cabin
  password: cabinpw
  charset: utf8
  db_name: sensor
  max_open_connection: 5
  max_idle_connection: 2
  max_lifetime_connection: 60s
  db_migrate: false
kafka:
  host: host.docker.internal
  port: 9092
mqtt:
  host: host.docker.internal
  port: 1883